CREATE OR REPLACE VIEW EAI.VW_EAI_USERMESSAGE
(MESSAGEID, USERID, TYPE)
AS 
SELECT MS.MESSAGEID,  USM.USERID , MS.TYPE
FROM USERMESSAGE USM
LEFT OUTER JOIN EAI_TASK ET ON  USM.MESSAGEID = ET.MESSAGEID AND USM.USERID = ET.USERID
INNER JOIN MESSAGE MS ON MS.MESSAGEID = USM.MESSAGEID
WHERE ET.TASKID IS NULL;

