CREATE OR REPLACE VIEW EAI.VW_EAI_USERMESSAGE
(CODICE, TYPE)
AS 
SELECT  USM.USERMESSAGEID as CODICE,  MS.TYPE
FROM USERMESSAGE USM
LEFT OUTER JOIN EAI_TASK ET ON  USM.USERMESSAGEID = ET.VALORE  
INNER JOIN MESSAGE MS ON MS.MESSAGEID = USM.MESSAGEID
WHERE ET.ID IS NULL;