CREATE TABLE EAI.USERS
(
  USERID          NUMBER                        NOT NULL,
  NOME            VARCHAR2(50 CHAR),
  COGNOME         VARCHAR2(50 CHAR),
  TELEFONO        VARCHAR2(12 CHAR),
  EMAILPRIVATE    VARCHAR2(30 CHAR),
  EMAILPUBBLICHE  VARCHAR2(30 CHAR)
);


ALTER TABLE EAI.USERS ADD (
  CONSTRAINT USER_PK
  PRIMARY KEY
  (USERID));
CREATE TABLE EAI.MESSAGE
(
  MESSAGEID   NUMBER                            NOT NULL,
  TITLE       VARCHAR2(50 CHAR),
  BODY        VARCHAR2(300 CHAR),
  DATESTART   DATE,
  DATEFINISH  DATE,
  TYPE        NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


ALTER TABLE EAI.MESSAGE ADD (
  CONSTRAINT MESSAGE_PK
  PRIMARY KEY
  (MESSAGEID));
CREATE TABLE EAI.USERMESSAGE
(
  USERMESSAGEID  NUMBER                         NOT NULL,
  MESSAGEID      NUMBER,
  USERID         NUMBER
);


ALTER TABLE EAI.USERMESSAGE ADD (
  CONSTRAINT USERMESSAGE_PK
  PRIMARY KEY
  (USERMESSAGEID));

ALTER TABLE EAI.USERMESSAGE ADD (
  CONSTRAINT USERMESSAGE_R01 
  FOREIGN KEY (MESSAGEID) 
  REFERENCES EAI.MESSAGE (MESSAGEID),
  CONSTRAINT USERMESSAGE_R02 
  FOREIGN KEY (USERID) 
  REFERENCES EAI.USERS (USERID));

CREATE TABLE EAI.EAI_TASK
(
  TASKID     NUMBER                             NOT NULL,
  MESSAGEID  NUMBER,
  USERID     NUMBER,
  TYPE       INTEGER,
  STATUS     INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


ALTER TABLE EAI.EAI_TASK ADD (
  CONSTRAINT EAI_TASK_PK
  PRIMARY KEY
  (TASKID));


